name: 'Setup Android Environment'
description: 'Checks out the code and sets up the specified Java version.'
runs:
  using: "composite"
  steps:
    # Set up the Java Development Kit (JDK)
    # 25 is the latest, but for stability concern, I decided to use the
    # Long-Term Support (LTS) version.
    # Eclipse Temurin is the mot recommended distributor, so I am using it.
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'