package com.mygroup.buzzguy

import android.content.Context
import android.util.Log
import com.google.firebase.FirebaseApp
import com.google.firebase.appcheck.FirebaseAppCheck
import com.google.firebase.appcheck.debug.DebugAppCheckProviderFactory
import androidx.core.content.edit

class DebugAppCheckInstaller(private val context: Context) : AppCheckProviderFactoryInstaller {
    override fun install(firebaseAppCheck: FirebaseAppCheck) {
        Log.d("AppCheckSetup", "Build is DEBUG. Installing DebugAppCheckProviderFactory.")

        // Use the token generated by your build.gradle
        val debugToken = BuildConfig.FIREBASE_APP_CHECK_DEBUG_TOKEN
        if (debugToken.isNotEmpty()) {
            // ... (Your SharedPreferences workaround logic from CustomApplication.kt goes here)
            val prefs = context.getSharedPreferences(
                "com.google.firebase.appcheck.debug.store." + FirebaseApp.getInstance().persistenceKey,
                Context.MODE_PRIVATE
            )
            prefs.edit { putString("com.google.firebase.appcheck.debug.DEBUG_SECRET", debugToken) }
        }

        firebaseAppCheck.installAppCheckProviderFactory(
            DebugAppCheckProviderFactory.getInstance()
        )
    }
}
